<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PCSC" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
    <PackageReference Include="System.Text.Json" Version="8.0.2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Tests/**" />
    <Compile Remove="Examples/**" />
    <Compile Remove="NFC_Test/**" />
    <Compile Remove="PCSC_Test/**" />
    <Compile Remove="SCardState_Test/**" />
    <Compile Remove="PCSC_API_Test/**" />
  </ItemGroup>

</Project>
